dist: bionic # Ubuntu 18.04
language: cpp
env:
  global:
    - PROC=2
    - MAKEFLAGS="-j ${PROC}"
    - DEPS_BUILD_DIR="${HOME}/deps"
    - DEPS_INSTALL_DIR="${HOME}/install"
    - BUILD_TYPE=Release
    - OPENCV_VERSION="3.4.10"
matrix:
  # fast_finish: true
  include:
    # - os: linux
      # addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
          # packages:
            # - g++-6
      # env:
        # - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"
    
install:
  - chmod ugo+x tools/travis/cmake.sh
  - chmod ugo+x tools/travis/opencv.sh

  - . ./tools/travis/cmake.sh
  - . ./tools/travis/opencv.sh

before_script:
  - mkdir build && cd build
  - cmake ..

script:
  - cmake --build . --config ${BUILD_TYPE} --parallel ${PROC}
  - bin/ECVL_TESTS

cache:
  directories:
    - ${DEPS_INSTALL_DIR}/