.TH "DefaultMemoryManager" 3 "Thu May 16 2019" "ECVL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefaultMemoryManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMemoryManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual uint8_t * \fBAllocate\fP (size_t nbytes) override"
.br
.ti -1c
.RI "virtual void \fBDeallocate\fP (uint8_t *data) override"
.br
.ti -1c
.RI "virtual uint8_t * \fBAllocateAndCopy\fP (size_t nbytes, uint8_t *src) override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDefaultMemoryManager\fP * \fBGetInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file memorymanager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECVL from the source code\&.
