.TH "ecvl::MetaData" 3 "Thu May 16 2019" "ECVL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecvl::MetaData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBQuery\fP (const std::string &name, std::string &value) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECVL from the source code\&.
