.TH "ecvl::Img< T >" 3 "Thu May 16 2019" "ECVL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecvl::Img< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBecvl::Image\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImg\fP (\fBImage\fP &img)"
.br
.ti -1c
.RI "T & \fBoperator()\fP (int x, int y)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class ecvl::Img< T >"

.PP
Definition at line 148 of file core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECVL from the source code\&.
