.TH "filesystem::path" 3 "Thu May 16 2019" "ECVL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filesystem::path
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpath\fP (const std::string &p)"
.br
.ti -1c
.RI "\fBpath\fP & \fBoperator/=\fP (const \fBpath\fP &p)"
.br
.ti -1c
.RI "\fBpath\fP & \fBoperator=\fP (const std::string &s)"
.br
.ti -1c
.RI "\fBpath\fP & \fBoperator=\fP (const \fBpath\fP &p)"
.br
.ti -1c
.RI "std::string \fBstring\fP () const"
.br
.ti -1c
.RI "\fBpath\fP \fBparent_path\fP () const"
.br
.ti -1c
.RI "\fBpath\fP \fBstem\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file filesystem\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECVL from the source code\&.
