name: macos

on: [push, pull_request]

env:
  BUILD_TYPE: "Release"
  OPENCV_VERSION: "3.4.13"
  EDDL_VERSION: "v0.8.3a"
  PROC: 2

jobs:
  build:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg:
          - { os: macos-10.15, c-version: clang, cxx-version: clang++, generator: "Xcode" }
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install compiler
        run: |
          echo "CC=${{ matrix.cfg.c-version }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.cfg.cxx-version }}" >> $GITHUB_ENV

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}/deps_install
          key: ${{ runner.os }}-${{ matrix.cfg.c-version }}-${{ env.EDDL_VERSION }}-${{ env.OPENCV_VERSION }}-cache-deps

      - name: Install dependencies
        env:
          CACHE: "${{ steps.cache-deps.outputs.cache-hit }}"
          CMAKE_GENERATOR: ${{ matrix.cfg.generator }}
          DEPS_INSTALL_PATH: ${{ runner.workspace }}/deps_install
          DEPS_PATH: ${{ runner.workspace }}/deps
          OS: ${{ runner.os }}
        run: |
          brew install openslide
          chmod +x ci/deps.sh
          ci/deps.sh

      - name: Configure and build
        env:
          CMAKE_GENERATOR: ${{ matrix.cfg.generator }}
          DEPS_INSTALL_PATH: ${{ runner.workspace }}/deps_install
        run: |
          mkdir -p build && cd build
          OpenCV_DIR=${DEPS_INSTALL_PATH}/opencv/share/OpenCV
          cmake -G"${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DECVL_SHARED=OFF -DOpenCV_DIR=${OpenCV_DIR} -Deddl_DIR=${DEPS_INSTALL_PATH}/eddl-${EDDL_VERSION}/build/install/lib/cmake/eddl -DECVL_BUILD_EDDL=ON -DECVL_DATASET=ON -DECVL_WITH_DICOM=ON -DECVL_WITH_OPENSLIDE=ON -DOPENSLIDE_INCLUDE_DIRECTORIES=${OPENSLIDE_INCLUDE_DIRECTORIES} -DOPENSLIDE_LIBRARIES=${OPENSLIDE_LIBRARIES} -DECVL_GPU=OFF ..
          cmake --build . --config ${BUILD_TYPE} --parallel ${PROC}

      - name: Test
        run: |
          cd build
          ctest -C ${BUILD_TYPE} -VV
